import {
  LayoutDashboard,
  Book,
  Library,
  Heart,
  Settings,
  Users,
  FileText,
  Calendar,
  Building,
  Building2,
  BarChart,
  GraduationCap,
  BookOpen,
  Mail,
  MessageSquare,
  Bell,
  Search,
  ShoppingBag,
  Home,
  User,
  Shield,
  Briefcase,
  Layers,
  PieChart,
  CreditCard,
  HelpCircle,
  FileQuestion,
  Clipboard,
  Newspaper,
  Award,
  Bookmark,
  Truck,
  Map,
  Headphones,
  Video,
  Image,
  Folder,
  FolderLock,
  Database,
  Server,
  Code,
  Terminal,
  Cloud,
  Lock,
  Key,
  UserLock,
  GlobeLock,
  Boxes,
  Waypoints,
  View,
  MonitorSmartphone,
  MonitorCheck,
  TabletSmartphone,
  ServerCog,
  CalendarCheck,
  BookLock,
  NotebookTabs,
  DoorOpen,
  ListMinus,
  Unplug,
  Atom,
  List,
  SquarePlus,
  UserPen,
  UtensilsCrossed,
  ChefHat,
  Play,
  Activity,
  BellElectric,
  Soup,
  Waves,
  LibraryBig,
  ClipboardPaste,
  Hospital,
  CircleDollarSign,
  HandHeart,
  Info,
  Plus,
  Clock,
  ShieldUser,
  SquareChartGantt,
  Ambulance,
  Gauge,
} from 'lucide-react';
export const iconMap = {
  dashboard: LayoutDashboard,
  userLock: UserLock,
  globeLock: GlobeLock,
  book: Book,
  library: Library,
  heart: Heart,
  settings: Settings,
  users: Users,
  fileText: FileText,
  calendar: Calendar,
  building: Building,
  building2: Building2,
  barChart: BarChart,
  graduationCap: GraduationCap,
  bookOpen: BookOpen,
  mail: Mail,
  messageSquare: MessageSquare,
  bell: Bell,
  search: Search,
  shoppingBag: ShoppingBag,
  home: Home,
  user: User,
  shield: Shield,
  briefcase: Briefcase,
  layers: Layers,
  pieChart: PieChart,
  creditCard: CreditCard,
  helpCircle: HelpCircle,
  fileQuestion: FileQuestion,
  clipboard: Clipboard,
  newspaper: Newspaper,
  award: Award,
  bookmark: Bookmark,
  truck: Truck,
  map: Map,
  headphones: Headphones,
  video: Video,
  image: Image,
  folder: Folder,
  folderLock: FolderLock,
  database: Database,
  server: Server,
  code: Code,
  terminal: Terminal,
  cloud: Cloud,
  lock: Lock,
  key: Key,
  boxes: Boxes,
  route: Waypoints,
  view: View,
  device: MonitorSmartphone,
  deviceAdmin: MonitorCheck,
  devices: TabletSmartphone,
  service: ServerCog,
  attendance: CalendarCheck,
  bookLock: BookLock,
  slot: NotebookTabs,
  rooms: DoorOpen,
  list: ListMinus,
  connect: Unplug,
  course: Atom,
  lists: List,
  add: SquarePlus,
  instructor: UserPen,
  mess: UtensilsCrossed,
  vendor: ChefHat,
  session: Play,
  active: Activity,
  hostel: BellElectric,
  soup: Soup,
  wave: Waves,
  books: LibraryBig,
  checkout: ClipboardPaste,
  hospital: Hospital,
  dollar: CircleDollarSign,
  insurance: HandHeart,
  info: Info,
  plus: Plus,
  clock: Clock,
  doctor: ShieldUser,
  slots: SquareChartGantt,
  ambulance: Ambulance,
  workbench: Gauge,
};
