"""finance init

Revision ID: 6d5fa9d70dc0
Revises: 5d7b7536b4d0
Create Date: 2026-01-04 14:24:09.513393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5fa9d70dc0'
down_revision: Union[str, None] = '5d7b7536b4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=True)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=True)
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_created_by'), 'group', ['created_by'], unique=False)
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=True)
    op.create_table('group_expense',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('paid_by', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('split_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_expense_group_id'), 'group_expense', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_expense_id'), 'group_expense', ['id'], unique=True)
    op.create_index(op.f('ix_group_expense_paid_by'), 'group_expense', ['paid_by'], unique=False)
    op.create_table('group_member',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_member_group_id'), 'group_member', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_member_id'), 'group_member', ['id'], unique=True)
    op.create_index(op.f('ix_group_member_user_id'), 'group_member', ['user_id'], unique=False)
    op.create_table('settlement',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_from_user_id'), 'settlement', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_settlement_group_id'), 'settlement', ['group_id'], unique=False)
    op.create_index(op.f('ix_settlement_id'), 'settlement', ['id'], unique=True)
    op.create_index(op.f('ix_settlement_to_user_id'), 'settlement', ['to_user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_account_id'), 'subscription', ['account_id'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=True)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('expense_split',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_expense_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('share_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_expense_id'], ['group_expense.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_split_group_expense_id'), 'expense_split', ['group_expense_id'], unique=False)
    op.create_index(op.f('ix_expense_split_id'), 'expense_split', ['id'], unique=True)
    op.create_index(op.f('ix_expense_split_user_id'), 'expense_split', ['user_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('related_account_id', sa.String(), nullable=True),
    sa.Column('group_expense_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['group_expense_id'], ['group_expense.id'], ),
    sa.ForeignKeyConstraint(['related_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_category_id'), 'transaction', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_group_expense_id'), 'transaction', ['group_expense_id'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=True)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('linked_transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=True)
    op.create_index(op.f('ix_attachment_linked_transaction_id'), 'attachment', ['linked_transaction_id'], unique=False)
    op.create_index(op.f('ix_attachment_user_id'), 'attachment', ['user_id'], unique=False)
    op.add_column('user', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('user', sa.Column('default_currency', sa.String(), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'default_currency')
    op.drop_column('user', 'timezone')
    op.drop_index(op.f('ix_attachment_user_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_linked_transaction_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_group_expense_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_category_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_expense_split_user_id'), table_name='expense_split')
    op.drop_index(op.f('ix_expense_split_id'), table_name='expense_split')
    op.drop_index(op.f('ix_expense_split_group_expense_id'), table_name='expense_split')
    op.drop_table('expense_split')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_account_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_settlement_to_user_id'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_id'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_group_id'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_from_user_id'), table_name='settlement')
    op.drop_table('settlement')
    op.drop_index(op.f('ix_group_member_user_id'), table_name='group_member')
    op.drop_index(op.f('ix_group_member_id'), table_name='group_member')
    op.drop_index(op.f('ix_group_member_group_id'), table_name='group_member')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_group_expense_paid_by'), table_name='group_expense')
    op.drop_index(op.f('ix_group_expense_id'), table_name='group_expense')
    op.drop_index(op.f('ix_group_expense_group_id'), table_name='group_expense')
    op.drop_table('group_expense')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_index(op.f('ix_group_created_by'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
